name: rdm_webhook

services:
  rdm-webhook:
    build:
      context: .
      dockerfile: Dockerfile.webhook
    container_name: rdm-webhook
    restart: unless-stopped
    init: true
    env_file:
      - ./deploy/webhook.env
    environment:
      PROJECT_DIR: /repo
      DEPLOY_BRANCH: refactor-bot-structure
      APP_COMPOSE_PROJECT_NAME: rdm_bot
      DEPLOY_LOG_FILE: /repo/deploy.log
    ports:
      - "9000:9000"
    volumes:
      - ./:/repo
      - /var/run/docker.sock:/var/run/docker.sock
